source 'https://rubygems.org'

gemspec

gem 'standalone_migrations', git: 'https://github.com/dmolesUC3/standalone-migrations.git', ref: 'f1cbfc9'

path '..' do
  gem 'stash-harvester'
  gem 'stash-sword'
  gem 'stash-wrapper'
  gem 'stash_datacite'
  gem 'stash_discovery'
  gem 'stash_engine'
end

